"""LLM copilot briefing library — the pipeline-time generator behind the sidebar.

Reads the served marts, fetches recent headlines for held tickers, asks a local
LLM (Ollama) for a ~3-paragraph analyst briefing, validates it, and writes the
result as the `copilot_briefing` table in the active marts dataset. The app
never imports this module: it reads the finished table through data.py's seam.
Design: docs/llm_copilot_briefing_design.md.

Privacy rule (structural): real-portfolio briefings may only be generated by a
provider that declares `is_local=True` — the data never leaves the machine,
mirroring the prod-private dataset isolation.

Grounding rule: every number the model may cite comes from the DATA section of
the prompt packet; NEWS is qualitative color only. The numeric audit checks the
briefing's cited figures against the packet after generation.

Import discipline: module-level imports are stdlib + pandas only. requests,
yfinance, and google.cloud.bigquery load lazily inside the functions that need
them, so importing this module never requires the pipeline stack (the Streamlit
deploy's requirements deliberately lack it).
"""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Protocol

import pandas as pd

PROJECT = "anchor-495115"
BRIEFING_TABLE = "copilot_briefing"
DEFAULT_MODEL = "qwen3:30b-a3b-instruct-2507-q4_K_M"
DEFAULT_OLLAMA_HOST = "http://localhost:11434"

# The numeric backbone: five served marts plus the shared trading calendar.
CONTEXT_TABLES = [
    "as_of_calendar",
    "macro_regime",
    "macro_indicators",
    "sector_performance",
    "portfolio_composition",
    "holdings_benchmarks",
]

NEWS_MAX_AGE_DAYS = 7
NEWS_PER_TICKER = 3
NEWS_TOTAL_CAP = 20

# Section markers shared by build_context and the numeric audit so the packet
# format and the audit's DATA/NEWS split can never drift apart.
DATA_HEADER = "# DATA"
NEWS_HEADER = "# NEWS"

# Hard-failure length bounds. These catch pathology (an empty refusal, a
# runaway generation), not style — typical output runs ~1.5-2.5k chars.
MIN_BRIEFING_CHARS = 200
MAX_BRIEFING_CHARS = 4000

ARTIFACT_COLUMNS = [
    "horizon",
    "briefing_md",
    "as_of_date",
    "generated_at",
    "provider",
    "model",
    "sources",
]


class BriefingError(RuntimeError):
    """Base failure for briefing generation; the CLI maps it to exit 1."""


class PrivacyError(BriefingError):
    """A real-portfolio briefing was requested from a non-local provider."""


class ValidationError(BriefingError):
    """The generated briefing failed a hard validation check; nothing was written."""


# --- provider seam ------------------------------------------------------------


class BriefingProvider(Protocol):
    """Anchor's own tiny provider interface (deliberately not an OpenAI shim).

    A future AnthropicProvider (official SDK, is_local=False) drops in here;
    the generator's privacy guard keys off `is_local`.
    """

    name: str
    is_local: bool
    model: str

    def generate(self, system: str, prompt: str) -> str: ...


class OllamaProvider:
    """Local Ollama over HTTP. The only provider shipped in v1."""

    name = "ollama"
    is_local = True

    def __init__(
        self,
        model: str | None = None,
        host: str | None = None,
        timeout: int = 300,
        temperature: float = 0.2,
    ):
        self.model = model or os.environ.get("ANCHOR_BRIEFING_MODEL", DEFAULT_MODEL)
        self.host = (host or os.environ.get("OLLAMA_HOST", DEFAULT_OLLAMA_HOST)).rstrip("/")
        self.timeout = timeout
        self.temperature = temperature

    def generate(self, system: str, prompt: str) -> str:
        import requests  # lazy: not part of the app deploy's requirements

        try:
            resp = requests.post(
                f"{self.host}/api/chat",
                json={
                    "model": self.model,
                    "messages": [
                        {"role": "system", "content": system},
                        {"role": "user", "content": prompt},
                    ],
                    "stream": False,
                    "options": {"temperature": self.temperature},
                },
                timeout=self.timeout,
            )
        except requests.exceptions.ConnectionError as exc:
            raise BriefingError(
                f"Ollama not reachable at {self.host} — is `ollama serve` running?"
            ) from exc
        resp.raise_for_status()
        return resp.json()["message"]["content"].strip()


# --- inputs: marts + news -----------------------------------------------------


def build_bigquery_client():
    """Keyfile when present, ADC otherwise — same resolution as the ingesters,
    but honoring GOOGLE_APPLICATION_CREDENTIALS like data.py."""
    from google.cloud import bigquery  # lazy

    key_path = os.environ.get(
        "GOOGLE_APPLICATION_CREDENTIALS",
        str(Path.home() / ".dbt" / "anchor-bigquery-key.json"),
    )
    if Path(key_path).exists():
        return bigquery.Client.from_service_account_json(key_path, project=PROJECT)
    return bigquery.Client(project=PROJECT)


def read_marts(client, dataset: str) -> dict[str, pd.DataFrame]:
    """Read the context tables from one marts dataset (demo or private)."""
    return {
        t: client.query(f"select * from `{PROJECT}.{dataset}.{t}`").to_dataframe()
        for t in CONTEXT_TABLES
    }


def held_tickers(composition: pd.DataFrame) -> list[str]:
    """Tickers worth fetching news for: market-valued, non-cash holdings,
    weight-descending — so the total news cap keeps the biggest positions'
    headlines. Cash pseudo-rows and source-valued alts have no public news."""
    df = composition.sort_values("weight_pct", ascending=False)
    mask = (df["valuation_source"] == "market") & (df["asset_class"] != "cash")
    return df.loc[mask, "ticker"].dropna().unique().tolist()


def _parse_news_items(
    ticker: str,
    raw_items: list[dict],
    *,
    now: datetime | None = None,
    max_age_days: int = NEWS_MAX_AGE_DAYS,
    per_ticker: int = NEWS_PER_TICKER,
) -> list[dict]:
    """Pure parser for yfinance's nested-`content` news payload.

    Skips malformed items (no content/title/pubDate), drops anything older
    than `max_age_days`, and returns at most `per_ticker` items, newest first.
    `now` is injectable so tests can pin recency without a live clock.
    """
    now = now or datetime.now(timezone.utc)
    cutoff = now - timedelta(days=max_age_days)
    parsed = []
    for item in raw_items or []:
        content = item.get("content") or {}
        title, pub = content.get("title"), content.get("pubDate")
        if not title or not pub:
            continue
        try:
            pub_dt = pd.to_datetime(pub, utc=True)
        except (ValueError, TypeError):
            continue
        if pub_dt < cutoff:
            continue
        parsed.append(
            {
                "ticker": ticker,
                "title": title,
                "summary": (content.get("summary") or "")[:200],
                "provider": (content.get("provider") or {}).get("displayName", "unknown"),
                "pub_date": str(pub_dt.date()),
                "_pub_dt": pub_dt,
            }
        )
    parsed.sort(key=lambda n: n["_pub_dt"], reverse=True)
    for n in parsed:
        del n["_pub_dt"]
    return parsed[:per_ticker]


def fetch_news(
    tickers: list[str],
    *,
    per_ticker: int = NEWS_PER_TICKER,
    total_cap: int = NEWS_TOTAL_CAP,
    max_age_days: int = NEWS_MAX_AGE_DAYS,
) -> list[dict]:
    """Live headlines for held tickers. News is color, never fatal: any
    per-ticker failure is skipped silently rather than failing the refresh."""
    import yfinance as yf  # lazy

    items: list[dict] = []
    for ticker in tickers:
        if len(items) >= total_cap:
            break
        try:
            raw = yf.Ticker(ticker).news
        except Exception:
            continue
        items.extend(
            _parse_news_items(
                ticker, raw, max_age_days=max_age_days, per_ticker=per_ticker
            )
        )
    return items[:total_cap]


# --- the prompt packet ----------------------------------------------------------

_INDICATOR_LABELS = {
    "fed_funds_rate": "Fed Funds Rate",
    "ten_year_yield": "10-Year Treasury",
    "inflation_yoy": "Inflation (YoY)",
    "unemployment_rate": "Unemployment",
}


def _fmt(value, spec: str) -> str | None:
    """Format a number, or None when it's missing — a NaN must never surface
    as the literal string 'nan' in the packet."""
    if value is None or pd.isna(value):
        return None
    return format(value, spec)


def build_context(marts: dict[str, pd.DataFrame], news: list[dict]) -> str:
    """The dense prompt packet — a PURE function of DataFrames + headlines.

    The formatting here is load-bearing: the numeric audit treats the DATA
    section's %/pp figures as the complete vocabulary of citable numbers, so
    every quantity carries an explicit unit exactly as the model should quote
    it. (A unit-less delta once made the model spell out "percentage points",
    which escaped the audit regex.)
    """
    cal = marts["as_of_calendar"].iloc[0]
    regime = marts["macro_regime"].iloc[0]
    indicators = marts["macro_indicators"]
    sectors = marts["sector_performance"].sort_values("return_1m_pct", ascending=False)
    composition = marts["portfolio_composition"].sort_values("weight_pct", ascending=False)
    benchmarks = marts["holdings_benchmarks"]

    as_of = pd.to_datetime(cal["as_of_date"]).date()
    lines = [f"{DATA_HEADER} (every number you may cite — as of {as_of})", ""]

    lines += [
        "## Macro regime",
        f"{regime['regime_summary']}. Rates: {regime['rates_state']} · "
        f"Inflation: {regime['inflation_state']} · Labor: {regime['labor_state']}.",
        "",
        "## Macro indicators (current, 3-month change, direction)",
    ]
    for _, r in indicators.iterrows():
        label = _INDICATOR_LABELS.get(r["indicator_key"], r["indicator_key"])
        current, delta = _fmt(r["current_value"], ".2f"), _fmt(r["delta_3mo"], "+.2f")
        if current is None:
            continue
        change = f" (3-mo change {delta} pp, {r['direction']})" if delta else ""
        lines.append(f"- {label}: {current}%{change}")

    lines += ["", "## Sector performance (SPDR sector ETFs)"]
    for _, r in sectors.iterrows():
        rets = ", ".join(
            f"{h.upper()} {v}%"
            for h in ("1m", "ytd", "1y")
            if (v := _fmt(r[f"return_{h}_pct"], "+.2f")) is not None
        )
        lines.append(f"- {r['sector']} ({r['etf_ticker']}): {rets} — {r['rate_comovement_label']}")

    alloc = (
        composition.groupby("asset_class")["weight_pct"].sum().sort_values(ascending=False)
    )
    lines += [
        "",
        "## Portfolio allocation",
        " · ".join(f"{k}: {v:.1f}%" for k, v in alloc.items()),
        "",
        f"## Holdings ({len(composition)} positions, by weight)",
    ]
    for _, r in composition.iterrows():
        head = f"- {r['ticker']} — {r['description']} ({r['asset_class']}, {r['weight_pct']:.1f}% of portfolio)"
        if r["valuation_source"] != "market":
            lines.append(f"{head}: valued at source; no market returns")
            continue
        rets = ", ".join(
            f"{h.upper()} {v}%"
            for h in ("1m", "ytd", "1y")
            if (v := _fmt(r[f"return_{h}_pct"], "+.2f")) is not None
        )
        gain = _fmt(r["unrealized_gain_pct"], "+.2f")
        tail = (rets or "no return history yet") + (f"; unrealized {gain}%" if gain else "")
        lines.append(f"{head}: {tail}")
        axes = benchmarks[benchmarks["holding_ticker"] == r["ticker"]].sort_values("benchmark_type")
        for _, b in axes.iterrows():
            rel = ", ".join(
                f"{h.upper()} {v} pp"
                for h in ("1m", "ytd", "1y")
                if (v := _fmt(b[f"relative_{h}_pp"], "+.2f")) is not None
            )
            if rel:
                lines.append(f"  vs {b['benchmark_etf']} ({b['benchmark_type']}): {rel}")

    lines += [
        "",
        f"{NEWS_HEADER} (qualitative context ONLY — never cite numbers from this "
        "section; attribute the outlet)",
    ]
    if not news:
        lines.append("(no recent headlines)")
    for n in news:
        lines.append(f"- [{n['ticker']}] \"{n['title']}\" — {n['provider']}, {n['pub_date']}")
        if n.get("summary"):
            lines.append(f"  {n['summary']}")
    return "\n".join(lines)


SYSTEM_PROMPT = """You are Anchor's portfolio analyst, writing the owner's daily portfolio briefing.

Write about three short paragraphs of plain markdown — no headings, no bullet lists, no code fences. Use **bold** sparingly for tickers and key figures.

Follow the dashboard's reading order: the macro environment first, then sector context, then the portfolio's holdings. Weave the horizons (1M, YTD, 1Y) together like an analyst note rather than fixating on one.

The holdings paragraph is selective, not exhaustive: open with the portfolio's allocation shape, then discuss only the genuinely notable positions — the largest moves relative to their benchmarks and clear outliers. Index-tracking core positions deserve at most one sentence. Never recite every holding; the dashboard's table already does that.

Where a NEWS item relates to a holding or sector you discuss, weave in one or two of them as context, naming the outlet given in that NEWS item. Use only items from the NEWS section and never attribute anything to an outlet that is not listed there.

Grounding rules, non-negotiable:
- Every numeric claim must be copied verbatim from the DATA section, formatted exactly as it appears there. Write percentage-point differences as "pp" exactly as DATA does — never spell out "percentage points".
- Never compute, aggregate, total, extrapolate, average, or estimate numbers. If a figure is not printed in DATA, it does not exist.
- Before writing "outperformed" or "underperformed", check the sign of the pp figure you are citing: positive pp means the holding is ahead of that benchmark, negative means behind.
- When you describe a sector's rate relationship, quote its label exactly as given in DATA.
- The NEWS section is qualitative context only — never take numbers from it.
- If something is not in DATA, leave it out. Never invent.

You describe and explain; you do not advise. Never predict prices, rank trade opportunities, or recommend buying, selling, or holding. Distinguish measured facts from your interpretation. Keep the language calm and restrained — no urgency, no hype.

Output only the briefing markdown, nothing else."""


# --- validation -----------------------------------------------------------------


@dataclass
class ValidationResult:
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.errors


# A citable figure: a number immediately followed by % or pp (but not e.g.
# "ppm"). Signed exactly as printed. Plain unsuffixed numbers (years, counts)
# are deliberately out of scope.
_CITATION_RE = re.compile(r"[-+]?\d+(?:\.\d+)?(?=\s?(?:%|pp(?![A-Za-z])))")


def _citation_is_grounded(cited: str, allowed: set[str]) -> bool:
    """Decide whether one cited figure is backed by the DATA packet.

    `cited` is the numeric text exactly as the briefing wrote it (e.g. "3.2",
    "+5.00", "-0.36" — sign only if the model wrote one). `allowed` is every
    numeric string that appears with a %/pp unit in the DATA section, signed
    exactly as printed there (e.g. "+5.00", "4.17", "-0.36").

    Return True when the citation should count as grounded. This is the
    strictness-vs-false-positive dial for the whole audit: exact string match
    flags legitimate rounding ("3.2%" for a printed "3.21%"); a loose numeric
    tolerance lets fabricated figures slide. Sign handling is part of the
    decision too — prose like "down 0.36%" cites an unsigned number whose
    DATA form is "-0.36".
    """
    if cited in allowed:
        return True
    # Prose often omits the sign that DATA prints (e.g. "down 0.36%" vs "-0.36").
    cited_unsigned = cited.lstrip("+-")
    if any(a.lstrip("+-") == cited_unsigned for a in allowed):
        return True
    # Rounding tolerance (design-locked): the citation grounds when it could be
    # an allowed value rounded to the citation's printed precision — "3.2" and
    # "3" both ground against a printed "3.21".
    try:
        value = abs(float(cited))
    except ValueError:
        return False
    decimals = len(cited_unsigned.partition(".")[2])
    tolerance = max(0.5 * 10**-decimals, 0.05)
    return any(abs(abs(float(a)) - value) <= tolerance for a in allowed)


def _nearest_allowed(cited: str, allowed: set[str]) -> str | None:
    """The closest DATA figure to a flagged citation — printed in the warning
    so mismatches can be eyeballed quickly."""
    try:
        value = float(cited)
    except ValueError:
        return None
    best = min(allowed, key=lambda a: abs(float(a) - value), default=None)
    return best


def audit_numbers(briefing_md: str, context: str) -> list[str]:
    """Warning-level numeric audit: every %/pp figure the briefing cites should
    appear in the DATA section (NEWS numbers deliberately do not ground —
    numbers come from marts only). Returns human-readable mismatch strings."""
    data_section = context.split(NEWS_HEADER, 1)[0]
    allowed = set(_CITATION_RE.findall(data_section))
    warnings = []
    for cited in _CITATION_RE.findall(briefing_md):
        if not _citation_is_grounded(cited, allowed):
            nearest = _nearest_allowed(cited, allowed)
            hint = f" (nearest DATA figure: {nearest})" if nearest is not None else ""
            warnings.append(f"cited '{cited}' not found in the DATA packet{hint}")
    return warnings


def validate_briefing(briefing_md: str, context: str) -> ValidationResult:
    """Hard failures block the table write; warnings are logged (promotable to
    hard once the false-positive rate is known)."""
    result = ValidationResult()
    text = (briefing_md or "").strip()
    if not text:
        result.errors.append("briefing is empty")
        return result
    if not MIN_BRIEFING_CHARS <= len(text) <= MAX_BRIEFING_CHARS:
        result.errors.append(
            f"briefing length {len(text)} outside "
            f"[{MIN_BRIEFING_CHARS}, {MAX_BRIEFING_CHARS}]"
        )
    if "<think>" in text.lower() or "</think>" in text.lower():
        # Tripwire for accidentally swapping in a thinking-mode model.
        result.errors.append("briefing contains <think> tags")
    result.warnings.extend(audit_numbers(text, context))
    return result


# --- artifact + write -------------------------------------------------------------


def build_artifact(
    briefing_md: str,
    *,
    as_of_date,
    provider: BriefingProvider,
    news: list[dict],
    horizon: str = "all",
    generated_at: datetime | None = None,
) -> pd.DataFrame:
    """One artifact row. `sources` persists the headlines that were in the
    prompt — the audit trail for the qualitative claims."""
    sources = json.dumps(
        [
            {k: n[k] for k in ("ticker", "title", "provider", "pub_date")}
            for n in news
        ]
    )
    row = {
        "horizon": horizon,
        "briefing_md": briefing_md,
        "as_of_date": pd.to_datetime(as_of_date).date(),
        "generated_at": generated_at or datetime.now(timezone.utc),
        "provider": provider.name,
        "model": provider.model,
        "sources": sources,
    }
    return pd.DataFrame([row], columns=ARTIFACT_COLUMNS)


def write_briefing(client, dataset: str, artifact: pd.DataFrame) -> str:
    """WRITE_TRUNCATE the briefing table. Only ever called after validation
    passes, so a failed run leaves the previous briefing intact."""
    from google.cloud import bigquery  # lazy

    schema = [
        bigquery.SchemaField("horizon", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("briefing_md", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("as_of_date", "DATE", mode="REQUIRED"),
        bigquery.SchemaField("generated_at", "TIMESTAMP", mode="REQUIRED"),
        bigquery.SchemaField("provider", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("model", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("sources", "STRING", mode="NULLABLE"),
    ]
    job_config = bigquery.LoadJobConfig(
        schema=schema,
        write_disposition=bigquery.WriteDisposition.WRITE_TRUNCATE,
    )
    table_id = f"{PROJECT}.{dataset}.{BRIEFING_TABLE}"
    client.load_table_from_dataframe(artifact, table_id, job_config=job_config).result()
    return table_id


# --- orchestrator ------------------------------------------------------------------


def generate(
    portfolio: str,
    provider: BriefingProvider,
    client,
    *,
    skip_news: bool = False,
) -> dict[str, object]:
    """Full pipeline: guard -> read marts -> news -> packet -> LLM -> validate
    -> write. Raises PrivacyError / ValidationError / BriefingError; never
    writes on failure."""
    if portfolio not in ("demo", "real"):
        raise ValueError(f"portfolio must be 'demo' or 'real', got {portfolio!r}")
    # The privacy guard fires before ANY I/O: a real-portfolio briefing from a
    # hosted provider must be impossible, not merely unlikely.
    if portfolio == "real" and not provider.is_local:
        raise PrivacyError(
            f"real-portfolio briefings require a local provider; got "
            f"{provider.name!r} (is_local=False) — see docs/llm_copilot_briefing_design.md"
        )
    dataset = "anchor_marts_private" if portfolio == "real" else "anchor_marts"

    marts = read_marts(client, dataset)
    news = [] if skip_news else fetch_news(held_tickers(marts["portfolio_composition"]))
    context = build_context(marts, news)
    briefing_md = provider.generate(SYSTEM_PROMPT, context)

    result = validate_briefing(briefing_md, context)
    if not result.ok:
        raise ValidationError("briefing failed validation: " + "; ".join(result.errors))

    as_of = marts["as_of_calendar"]["as_of_date"].iloc[0]
    artifact = build_artifact(briefing_md, as_of_date=as_of, provider=provider, news=news)
    table_id = write_briefing(client, dataset, artifact)
    return {
        "table": table_id,
        "as_of_date": str(pd.to_datetime(as_of).date()),
        "chars": len(briefing_md),
        "headlines": len(news),
        "model": provider.model,
        "warnings": result.warnings,
    }
